config/routes.rb
Cma::Application.routes.draw do
  get "users/index"
  get "home/index"
  post "home/index"
  get "admin/index"
  post "admin/index"
  post "users/index"
  
  
  
  devise_for :users 

get '/:id', to: 'users#index'

resources :users

resources :contacts do
   member do
      get 'download'
    end
  resources :meetings do
    member do
      get 'download'
    end
  end
end

  root 'contacts#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_many :meetings
	belongs_to :user
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
	belongs_to :contact
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :contacts
 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    #@user = @contact.users.all
    @contacts = Contact.all
    #@meeting = @contacts.meetings.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  def download
    contactId = params[:id]
    if contactId != nil
      docContact = Contact.find(contactId)
      fileName = docContact.uploadDocuments
      saveContact = Rails.root.join('public', 'contactUpload', fileName)
      send_file(saveContact, fileName: docContact.uploadDocuments, type: "application/octet-stream")
    end
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    uploadedI = params[:contact][:docContact]
    if uploadedI != nil
    fileName = uploadedI.original_filename
    saveContact = Rails.root.join('public', 'contactUpload', fileName)
    File.open(saveContact,'wb') do |f|
      f.write(uploadedI.read)
      end
    @contact.uploadDocuments = fileName
    end
    
    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contact }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:firstName, :lastName, :streetAddress, :city, :state, :zip, :phoneNumber, :alternatePhoneNumber, :comments, :birthday, :uploadDocuments)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :authenticate_user!

  def index
  	
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
    @contact = Contact.find(params[:contact_id])
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @contact = Contact.find(params[:contact_id])
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
    @contact = Contact.find(params[:contact_id])
  end

  # GET /meetings/1/edit
  def edit
    @contact = Contact.find(params[:contact_id])
  end

  def download
    meetingId = params[:id]
    if meetingId != nil
      docMeeting = Meeting.find(meetingId)
      fileName = docMeeting.uploadDocuments
      saveMeeting = Rails.root.join('public', 'meetingUpload', fileName)
      send_file(saveMeeting, fileName: docMeeting.uploadDocuments, type: "application/octet-sream")
    end
  end

  # POST /meetings
  # POST /meetings.json
  def create
    #@meeting = @contact.meetings.new(meeting_params)
    @meeting = Meeting.new(meeting_params)
    @meeting.contact_id = params[:contact_id]
    @meeting.user_id = current_user.id
    uploadedI = params[:meeting][:docMeeting]
    if uploadedI != nil
    fileName = uploadedI.original_filename
    saveMeeting = Rails.root.join('public', 'meetingUpload', fileName)
    File.open(saveMeeting, 'wb') do |f|
      f.write(uploadedI.read)
      end
    @meeting.uploadDocuments = fileName
    end 
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to contact_meetings_path, notice: 'Meeting was successfully created.' }
        format.json { render action: 'show', status: :created, location: @meeting }
      else
        format.html { render action: 'new' }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to contact_meetings_path, notice: 'Meeting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to contact_meetings_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:purpose, :attendance, :timeAndDate, :location, :notes, :uploadDocuments)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :authenticate_user!

  def show
  @user = User.find_by_email(params[:id])
    if @user
     @contacts = @user.contacts.all
     render action: :show
    end
  end

end

#if current_user.user_type == nil
#        current_user.user_type == 'Basic'
 #       current_user.save
  #  end
   # if current_user.user_type == 'Premium'
    #    current_user.save
  #  end
 # end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstName %><br>
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br>
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :streetAddress %><br>
    <%= f.text_field :streetAddress %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :phoneNumber %><br>
    <%= f.text_field :phoneNumber %>
  </div>
  <div class="field">
    <%= f.label :alternatePhoneNumber %><br>
    <%= f.text_field :alternatePhoneNumber %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.text_field :birthday %>
  </div>
  <div class="field">
    <%= f.label :uploadDocuments %><br>
    <%= f.text_field :uploadDocuments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstName %><br>
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br>
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :streetAddress %><br>
    <%= f.text_field :streetAddress %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :phoneNumber %><br>
    <%= f.text_field :phoneNumber %>
  </div>
  <div class="field">
    <%= f.label :alternatePhoneNumber %><br>
    <%= f.text_field :alternatePhoneNumber %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.text_field :birthday %>
  </div>
  <div class="field">
    <%= f.label :uploadDocuments %><br>
    <%= f.file_field :docContact %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Streetaddress</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Phonenumber</th>
      <th>Alternatephonenumber</th>
      <th>Comments</th>
      <th>Birthday</th>
      <th>Uploaddocuments</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.firstName %></td>
        <td><%= contact.lastName %></td>
        <td><%= contact.streetAddress %></td>
        <td><%= contact.city %></td>
        <td><%= contact.state %></td>
        <td><%= contact.zip %></td>
        <td><%= contact.phoneNumber %></td>
        <td><%= contact.alternatePhoneNumber %></td>
        <td><%= contact.comments %></td>
        <td><%= contact.birthday %></td>
        <td><%= contact.uploadDocuments %></td>
        <td><%= link_to 'Download Document', download_contact_path(contact) %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstName %><br>
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br>
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :streetAddress %><br>
    <%= f.text_field :streetAddress %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :phoneNumber %><br>
    <%= f.text_field :phoneNumber %>
  </div>
  <div class="field">
    <%= f.label :alternatePhoneNumber %><br>
    <%= f.text_field :alternatePhoneNumber %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.text_field :birthday %>
  </div>
  <div class="field">
    <%= f.label :uploadDocuments %><br>
    <%= f.file_field :docContact %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @contact.firstName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @contact.lastName %>
</p>

<p>
  <strong>Streetaddress:</strong>
  <%= @contact.streetAddress %>
</p>

<p>
  <strong>City:</strong>
  <%= @contact.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @contact.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @contact.zip %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @contact.phoneNumber %>
</p>

<p>
  <strong>Alternatephonenumber:</strong>
  <%= @contact.alternatePhoneNumber %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @contact.comments %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @contact.birthday %>
</p>

<p>
  <strong>Uploaddocuments:</strong>
  <%= @contact.uploadDocuments %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Meeting', contact_meetings_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/home/index.html.erb
<h1>Log In / Signe Up</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cma</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div><p><%= link_to 'Signe_out', destroy_user_session_path, :method => :delete %></p>
		

</div>
<%= yield %>

</body>
</html>

app/views/meetings/_form.html.erb
<%= form_for(contact_meetings_path(@contact)) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :purpose %><br>
    <%= f.text_field :purpose %>
  </div>
  <div class="field">
    <%= f.label :attendance %><br>
    <%= f.text_field :attendance %>
  </div>
  <div class="field">
    <%= f.label :timeAndDate %><br>
    <%= f.text_field :timeAndDate %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :uploadDocuments %><br>
    <%= f.text_field :uploadDocuments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing meeting</h1>

<%= form_for(@meeting, url: contact_meeting_path(@contact, @meeting)) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :purpose %><br>
    <%= f.text_field :purpose %>
  </div>
  <div class="field">
    <%= f.label :attendance %><br>
    <%= f.text_field :attendance %>
  </div>
  <div class="field">
    <%= f.label :timeAndDate %><br>
    <%= f.text_field :timeAndDate %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :uploadDocuments %><br>
    <%= f.file_field :docMeeting %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Show', contact_meeting_path(@contact, @meeting) %> |
<%= link_to 'Back', contact_meetings_path(@contact, @meeting) %>

app/views/meetings/index.html.erb
<h1>Listing meetings</h1>

<table>
  <thead>
    <tr>
      <th>Purpose</th>
      <th>Attendance</th>
      <th>Timeanddate</th>
      <th>Location</th>
      <th>Notes</th>
      <th>Uploaddocuments</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.purpose %></td>
        <td><%= meeting.attendance %></td>
        <td><%= meeting.timeAndDate %></td>
        <td><%= meeting.location %></td>
        <td><%= meeting.notes %></td>
        <td><%= meeting.uploadDocuments %></td>
        <td><%= link_to 'Download Document', download_contact_meeting_path(@contact, meeting) %></td>
        <td><%= link_to 'Show', contact_meeting_path(@contact, meeting) %></td>
        <td><%= link_to 'Edit', edit_contact_meeting_path(@contact, meeting) %></td>
        <td><%= link_to 'Destroy', contact_meeting_path(@contact, meeting), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_contact_meeting_path(@contact) %> |
<%= link_to 'contacts', contacts_path %>

app/views/meetings/new.html.erb
<h1>New meeting</h1>

<%= form_for(@meeting, url: contact_meetings_path(@contact)) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :purpose %><br>
    <%= f.text_field :purpose %>
  </div>
  <div class="field">
    <%= f.label :attendance %><br>
    <%= f.text_field :attendance %>
  </div>
  <div class="field">
    <%= f.label :timeAndDate %><br>
    <%= f.text_field :timeAndDate %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :uploadDocuments %><br>
    <%= f.file_field :docMeeting %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Purpose:</strong>
  <%= @meeting.purpose %>
</p>

<p>
  <strong>Attendance:</strong>
  <%= @meeting.attendance %>
</p>

<p>
  <strong>Timeanddate:</strong>
  <%= @meeting.timeAndDate %>
</p>

<p>
  <strong>Location:</strong>
  <%= @meeting.location %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @meeting.notes %>
</p>

<p>
  <strong>Uploaddocuments:</strong>
  <%= @meeting.uploadDocuments %>
</p>

<%= link_to 'Edit', edit_contact_meeting_path(@contact, @meeting) %> |
<%= link_to 'Back', contact_meetings_path(@contact, @meeting) %>

app/views/users/show.html.erb
<div><p><%= current_user.email %></p></div>
<br>
<h1>Listing contacts</h1>

  <tbody>
    <% if @contacts %>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.firstName %></td>
        <td><%= contact.lastName %></td>
        <td><%= contact.streetAddress %></td>
      </tr>
      <% end %>
    <% end %>

  </tbody>

<br>

<%= link_to 'New Contact', new_contact_path %>